import numpy as np
import pandas as pd
import pytest

from neuro_py.lfp import CSD


def test_standard_csd_returns_channel_by_time_array() -> None:
    coordinates = np.arange(4, dtype=float) * 0.05
    data = coordinates[:, None] ** 2 * np.array([[1.0, 2.0, 3.0]])

    result = CSD.get_csd("unused", data, shank=0, method="StandardCSD", channel_offset=0.05)

    np.testing.assert_allclose(
        result[1:-1], -2 * np.array([[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]])
    )
    assert result.shape == data.shape


def test_standard_csd_uses_explicit_coordinates() -> None:
    coordinates = np.array([0.0, 0.04, 0.1, 0.18])
    data = coordinates[:, None] ** 2 * np.array([[1.0, 2.0]])

    result = CSD.get_csd(
        "unused", data, shank=0, method="StandardCSD", coords=coordinates
    )

    np.testing.assert_allclose(result[1:-1], -2 * np.array([[1.0, 2.0]] * 2))


def test_get_coords_rejects_layout_that_would_misalign_data(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    layout = pd.DataFrame({"shank": [0, 0, 0], "y": [100.0, 0.0, 50.0]})
    monkeypatch.setattr(CSD.loading, "load_probe_layout", lambda basepath: layout)

    with pytest.raises(ValueError, match="strictly increasing"):
        CSD.get_coords("unused", shank=0)


def test_delta_icsd_inverts_its_conductivity_aware_forward_model() -> None:
    coords = np.array([0.0, 0.05, 0.10])
    diam = 0.015
    sigma = 0.3
    sigma_top = 0.15
    true_csd = np.array([[1.0, 2.0], [-2.0, -4.0], [1.5, 3.0]])
    distance = np.abs(coords[:, None] - coords[None, :])
    image_distance = np.abs(coords[:, None] + coords[None, :])
    forward = (
        np.sqrt(distance**2 + (diam / 2) ** 2)
        - distance
        + (sigma - sigma_top)
        / (sigma + sigma_top)
        * (np.sqrt(image_distance**2 + (diam / 2) ** 2) - image_distance)
    ) / (2 * (sigma / 1000))

    result = CSD.get_csd(
        "unused",
        forward @ true_csd,
        shank=0,
        method="DeltaiCSD",
        coords=coords,
        diam=diam,
        sigma=sigma,
        sigma_top=sigma_top,
    )

    np.testing.assert_allclose(result, true_csd)


def test_kcsd_1d_matches_elephant_1_1_golden_fixture() -> None:
    """Golden contact estimate generated by Elephant 1.1.0 KCSD1D."""
    coords = np.arange(8, dtype=float) * 0.05
    data = np.exp(-((coords[:, None] - 0.15) / 0.07) ** 2) * np.array(
        [[1.0, 0.5, 0.2]]
    )

    result = CSD.get_csd(
        "unused", data, shank=0, method="KCSD1D", coords=coords
    )

    elephant_contact_estimate = np.array(
        [
            -160.428451,
            -199.038834,
            95.215112,
            294.858356,
            63.248525,
            -162.382460,
            -72.755904,
            42.098193,
        ]
    )
    np.testing.assert_allclose(
        result[:, 0], elephant_contact_estimate, rtol=0.02, atol=2.0
    )


def test_kd1csd_alias_warns_and_uses_kcsd(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(CSD, "get_coords", lambda basepath, shank: np.array([0.0, 0.05, 0.1]))
    data = np.arange(12, dtype=float).reshape(3, 4)

    with pytest.deprecated_call(match="KD1CSD"):
        legacy = CSD.get_csd("unused", data, shank=0, method="KD1CSD")
    current = CSD.get_csd("unused", data, shank=0, method="KCSD1D")

    np.testing.assert_allclose(legacy, current)


def test_csd_rejects_channel_time_orientation(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(CSD, "get_coords", lambda basepath, shank: np.array([0.0, 0.05, 0.1]))

    with pytest.raises(ValueError, match="first data dimension"):
        CSD.get_csd("unused", np.ones((4, 3)), shank=0, method="DeltaiCSD")
